spring.application.name=main
server.port=9000

# Force UTF-8 Encoding to prevent MalformedInputException
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true
server.tomcat.uri-encoding=UTF-8
